name: Postman Collection Run
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  postman:
    runs-on: ubuntu-latest
    name: Run Audit Log Tests
    steps:
      - uses: actions/checkout@v4

      - name: Run Postman Collection
        uses: postmanlabs/postman-cli-action@v1
        with:
          api-key: ${{ secrets.POSTMAN_API_KEY }}
          command: collection run 52238111-0a098266-965f-4e7d-8d67-66021c0ffc5b --environment 52983738-71da65c9-4c6b-4ac3-9a4c-c834dce42c20 --verbose
